name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


jobs:   
  
  build-and-push:

    runs-on: self-hosted
    strategy:
      matrix:
        environment: [DEV,PROD]

    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v4
            
      - name: Login to Docker Hub
        
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
        
      - name: Build and Tag Backend Docker image for DEV environment
        run: |
          git_hash=$(git rev-parse --short HEAD) &
          docker build . -t $DOCKER_USER/backend:${{ matrix.DEV }} --file Dockerfile &
          docker tag $DOCKER_USER/backend:${{ matrix.DEV }} $DOCKERS_USER/backend:${{ matrix.DEV }}:$git_hash
      - name: Docker Push
        run: |
          docker push $DOCKER_USER/backend:${{ matrix.DEV }} &
          docker push $DOCKER_USER/backend:${{matrix.DEV}}:$git_hash

      - name: Build and Tag Backend Docker image for PROD environment
        run: |
          git_hash=$(git rev-parse --short HEAD) &
          docker build . -t $DOCKER_USER/backend:${{ matrix.PROD }} --file Dockerfile & 
          docker tag $DOCKER_USER/backend:${{ matrix.PROD }} $DOCKERS_USER/backend:${{ matrix.PROD}}:$git_hash
      - name: Docker Push
        run: |
          docker push $DOCKER_USER/backend:${{ matrix.PROD }} &
          docker push $DOCKER_USER/backend:${{ matrix.PROD }}:$git_hash

