name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:   
  
  build:

    runs-on: self-hosted
    # environment:  
    #       name: dev 
    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v4
            
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
        
      - name: Build and Push Backend Docker image
        run: |
          docker build . -t $DOCKER_USER  --file Dockerfile 

    