name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  
env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


jobs:
  deployment:  
    name: Selecting dev environment 
    runs-on: self-hosted

  
    if: github.ref == 'refs/heads/dev'
    environment: dev
    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v4
            
      - name: Login to Docker Hub
        
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    

      - name: Build and Tag Backend Docker image for DEV environment
        run: |
            docker build . -t $DOCKER_USER/backend:${{ vars.DEV }} -t $DOCKER_USER/backend:$(git rev-parse --short "$GITHUB_SHA" )   --file Dockerfile
      - name: Docker Push
        run: |
            docker push $DOCKER_USER/backend:$(git rev-parse --short "$GITHUB_SHA" )
            docker push $DOCKER_USER/backend:dev

  prod:
    name: Selecting prod environment
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    environment: prod

    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v4
            
      - name: Login to Docker Hub
        
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    

      - name: Build and Tag Backend Docker image for PROD environment
        run: |
            docker build . -t $DOCKER_USER/backend:${{ vars.PROD }} --file Dockerfile 
      - name: Docker Push
        run: |
          (docker push $DOCKER_USER/backend:${{ vars.PROD }})
