name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


jobs:   
  
  build-and-push:

    runs-on: self-hosted
    strategy:
      matrix:
        environment: [DEV,PROD]

    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v4
            
      - name: Login to Docker Hub
        
        run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
        
      - name: Build and Tag Backend Docker image for DEV environment
        run: |
          (docker build . -t $DOCKER_USER/backend:${{ matrix.DEV }} --file Dockerfile) &
      - name: Docker Push
        run: |
          (docker push $DOCKER_USER/backend:${{ matrix.DEV }} )

      - name: Build and Tag Backend Docker image for PROD environment
        run: |
          (docker build . -t $DOCKER_USER/backend:${{ matrix.PROD }} --file Dockerfile) & 
      - name: Docker Push
        run: |
          (docker push $DOCKER_USER/backend:${{ matrix.PROD }} ) 

